site:
  title: Antora ARC42 Template
  start_page: arc42-template::index.adoc

content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
  - url: ./
    start_path: src/docs/arc42
    branches: [HEAD]
  - url: ./
    start_path: src/docs/req42
    branches: [HEAD]
  - url: ./
    start_path: src/docs/arc42-v0.5
    branches: [HEAD]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: css/vendor/tabs.css
    contents: ./node_modules/@asciidoctor/tabs/dist/css/tabs.css
  - path: js/vendor/tabs.js
    contents: ./node_modules/@asciidoctor/tabs/dist/js/tabs.js
  - path: partials/footer-scripts.hbs
    contents: |
      <script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
      <script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
      <script async src="{{{uiRootPath}}}/js/vendor/tabs.js"></script>
      {{#if env.SITE_SEARCH_PROVIDER}}
      {{> search-scripts}}
      {{/if}}
  - path: partials/head-styles.hbs
    contents: |
      <link rel="stylesheet" href="{{{uiRootPath}}}/css/site.css">
      <link rel="stylesheet" href="{{{uiRootPath}}}/css/vendor/tabs.css">
  - path: partials/header.hbs
    contents: |
      <nav class="navbar">
        <div class="navbar-brand">
          <a class="navbar-item" href="../..">Antora ARC42 Template</a>
          <button class="navbar-burger" aria-controls="topbar-nav" aria-expanded="false" aria-label="Toggle main menu">
            <span></span>
            <span></span>
            <span></span>
          </button>
        </div>
        <div id="topbar-nav" class="navbar-menu">
          <div class="navbar-end">
            <a class="navbar-item" href="#">Home</a>
            <a class="navbar-item" href="../../arc42-template/latest/">arc42</a>
            <a class="navbar-item" href="../../req42-template/latest/">req42</a>
            <a class="navbar-item" href="https://doctoolchain.org">docToolchain</a>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link" href="#">Products</a>
              <div class="navbar-dropdown">
                <a class="navbar-item" href="#">Product A</a>
                <a class="navbar-item" href="#">Product B</a>
                <a class="navbar-item" href="#">Product C</a>
              </div>
            </div>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link" href="#">Services</a>
              <div class="navbar-dropdown">
                <a class="navbar-item" href="#">Service A</a>
                <a class="navbar-item" href="#">Service B</a>
                <a class="navbar-item" href="#">Service C</a>
              </div>
            </div>
            <div class="navbar-item">
              <span class="control">
                <a class="button is-primary" href="#">Download</a>
              </span>
            </div>
          </div>
        </div>
      </nav>
    
asciidoc:
  attributes:
    sectanchors: true
  extensions:
  - '@asciidoctor/tabs'    

output:
  dir: build/antora
