:jbake-title: Domain Terminology
:jbake-type: page_toc
:jbake-status: published
:jbake-menu: req42
:jbake-order: 8
:filename: /modules/ROOT/pages/08_domain-terminology.adoc
ifndef::imagesdir[:imagesdir: ../assets/images]

ifndef::optimize-content[]
:toc:
endif::optimize-content[]
[[section-domain-terminology]]
== Domain Terminology

[role="re42help"]
****
.Content
A glossary of technical terms with definitions. The "ubiquitous language" of your domain

.Motivation
Terms from your domain appear in every epic, feature, or story. These terms should be clear to everyone involved. And that's why it is desirable to have a glossary of such terms for a project or product development. 

Make sure that everyone involved speaks a common language - and has access to agreed-upon definitions of terms instead of bringing new words into play in every meeting.

.Notations/Tools
Alphabetically ordered list of term definitions


// .More Information
//
// https://docs.req42.de/section-xxx in the online documentation
****

[cols="12,50" options="header"]
|===
|Term |Definition
| _<Term-1>_ |_<Definition-1>_  
| _<Term-2>_ |_<Definition-2>_  
|            |             
|===
