name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      DTC_HEADLES: true
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: chmod +x dtcw
      - name: install antora
        run: npm i -D -E -g antora
      - name: generateSite
        run: npx antora --fetch antora-playbook.yml
      - name: copyToPublic
        run: cp -r ./build/antora ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        #        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public